INSERT INTO role(id, name) VALUES(1,'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO role(id, name) VALUES(2,'ROLE_ADMIN') ON CONFLICT DO NOTHING;

INSERT INTO Status(id, name) VALUES(1,'IN PROGRESS') ON CONFLICT DO NOTHING;
INSERT INTO Status(id, name) VALUES(2,'CREATED') ON CONFLICT DO NOTHING;
INSERT INTO Status(id, name) VALUES(3,'DONE') ON CONFLICT DO NOTHING;
